### ISSUE TITLE
Broken colab link

### ISSUE THREAD

**Issue by Andrew-S-Rosen** [cernaklab/samples#1]
Thanks for sharing your code!!! :)

I just wanted to let you know that the Colab link appears to point to a Drive link for the ipynb instead of Colab.

There is also no `model.zip`.

**Comment by b-mahjour** [comment]
Fixed the link, thanks for the heads up.

Due to file size I was having an issue uploading model.zip to the repository, even with Git LFS. 

Instead, here's a google drive link to the file: https://drive.google.com/file/d/1zazFRO8QpfBK_c4uZ3RRpuOwfQASK83R/view?usp=sharing

Hopefully this helps everything run a bit more smoothly. Let me know if there's anything else, and thanks for your interest.

**Comment by Andrew-S-Rosen** [comment]
Thanks, @b-mahjour!

I'm not sure if you're looking for alternate suggestions, but for a file of this size I might suggest uploading it to Figshare (20 GB limit) or Zenodo (50 GB limit), which you can then link back to here if you're interested.

That would help preserve the data. As you may or may not have seen on Twitter, there has been a lot of interest in your paper ;)

**Comment by Andrew-S-Rosen** [comment]
I'll close this issue now that you've addressed it all. Thanks again for being open with code- and data-sharing! :)
