### ISSUE TITLE
A few minor additions to instructions

### ISSUE THREAD

**Issue by Andrew-S-Rosen** [cernaklab/samples#2]
Hi again @b-mahjour! Good news -- I was able to get it running!

Following up on #1, might I suggest a few minor changes to the instructions so new users can more easily try it out?
1. The `model.zip` should be unzipped such that there is a folder named `model` in the current working directory. The `model.ckpt-10429.index.gz` file should also be `gunzip`'d.
2. The user will need to `pip install sklearn` if not using collab. Might be worth adding to the list of `pip` installs.
3. You might want to replace the Zenodo record link with the DOI since the latter is permanent: https://doi.org/10.5281/zenodo.6391612.

Feel free to close this issue whenever you like.

---------------
Note to the user who may read this: If you have trouble installing `magenta`, try installing `python-rtmidi` first and then install `magenta`. Also, the current (7.3) release of `music21` is broken on PyPi, but other versions are fine.

**Comment by b-mahjour** [comment]
Great! 

I committed the suggested changes. Thanks for the help. 

I'm having dependency issues running locally, I think because I'm running an arm64/noarch installation of python. Trying to navigate a solution but I was mainly working on it using Colab anyways.

Let me know if there's anything else – would be happy to see people use the program without much hassle.

**Comment by Andrew-S-Rosen** [comment]
For what it's worth, I got it working just fine on Ubuntu via the Windows Subsytem for Linux, so that was a good sign.

**Comment by Andrew-S-Rosen** [comment]
@b-mahjour -- ah, I forgot. There was one more thing. I think `!gunzip model.zip` should probably be `!unzip model.zip`.
